import { PublicKey } from "@solana/web3.js";

const resourceMints = [
	"SiLiCA4xKGkyymB5XteUVmUeLqE4JGQTyWBpKFESLgh",
	"Nitro6idW5JCb2ysUPGUAvVqv3HmUR7NVH7NdybGJ4L",
	"tiorehR1rLfeATZ96YoByUkvNFsBfUUSQWgSH2mizXL",
	"TTNM1SMkM7VKtyPW6CNBZ4cg3An3zzQ8NVLS2HpMaWL",
	"aeroBCMu6AX6bCLYd1VQtigqZh8NGSjn54H1YSczHeJ",
	"FiELD9fGaCgiNMfzQKKZD78wxwnBHTwjiiJfsieb6VGb",
	"LUMACqD5LaKjs1AeuJYToybasTXoYQ7YkxJEc4jowNj",
	"PoWRYJnw3YDSyXgNtN3mQ3TKUMoUSsLAbvE8Ejade3u",
	"EMAGoQSP89CJV5focVjrpEuE4CeqJ4k1DouQW7gUu7yX",
	"HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp",
	"CPPRam7wKuBkYzN5zCffgNU17RKaeMEns4ZD83BqBVNR",
	"MASS9GqtJz6ABisAxcUn3FeR4phMqH1XfG6LPKJePog",
	"FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J",
	"GRAPHKGoKtXtdPBx17h6fWopdT5tLjfAP8cDJ1SvvDn4",
	"CoNDDRCNxXAMGscCdejioDzb6XKxSzonbWb36wzSgp5T",
	"EMiTWSLgjDVkBbLFaMcGU6QqFWzX9JX6kqs1UtUjsmJA",
	"CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X",
	"ironxrUhTEaBiR9Pgp6hy4qWx6V2FirDoXhsFP25GFP",
	"CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc",
	"PTCLSWbwZ3mqZqHAporphY2ofio8acsastaHfoP87Dc",
	"SDUsgfSZaDhhZ76U3ZgvtFiXsfnHbf2VrzYxjBZ5YbM",
	"DMNDKqygEN3WXKVrAD4ofkYBc4CKNRhFUbXP4VK7a944",
	"HYCBuSWCJ5ZEyANexU94y1BaBPtAX2kzBgGD2vES2t6M",
	"RABSXX6RcqJ1L5qsGY64j91pmbQVbsYRQuw1mmxhxFe",
	"SUBSVX9LYiPrzHeg2bZrqFSDSKkrQkiCesr6SjtdHaX",
	"FMWKb7YJA5upZHbu5FjVRRoxdDw2FYFAu284VqUGF9C2",
	"cwirGHLB2heKjCeTy4Mbp4M443fU4V7vy2JouvYbZna",
	"PoLYs2hbRt5iDibrkPT9e6xWuhSS45yZji5ChgJBvcB",
	"ELECrjC8m9GxCqcm4XCNpFvkS8fHStAvymS6MJbe3XLZ",
	"MAGNMDeDJLvGAnriBvzWruZHfXNwWHhxnoNF75AQYM5",
	"CRYSNnUd7cZvVfrEVtVNKmXiCPYdZ1S5pM5qG2FDVZHF",
	"STEELXLJ8nfJy3P4aNuGxyNRbWPohqHSwxY75NsJRGG",
	"ARCoQ9dndpg6wE2rRexzfwgJR3NoWWhpcww3xQcQLukg",
	"RCH1Zhg4zcSSQK8rw2s6rDMVsgBEWa4kiv1oLFndrN5",
	"fueL3hBZjLLLJHiFH9cqZoozTG3XQZ53diwFPwbzNim",
	"foodQJAztMzX1DKpLaiounNe2BDMds5RNuPC6jsNrDG",
	"tooLsNYLiVqzg8o4m3L2Uetbn62mvMWRqkog6PQeYKL",
	"ammoK8AkX2wnebQb35cDAZtTkvsXQbi82cGeTnUvvfK",
] as const;

export type ResourceMint = (typeof resourceMints)[number];

const resourceNames = [
	"Silica",
	"Nitrogen",
	"TitaniumOre",
	"Titanium",
	"Aerogel",
	"FieldStabilizer",
	"Lumanite",
	"PowerSource",
	"Electromagnet",
	"Hydrogen",
	"Copper",
	"Biomass",
	"IronOre",
	"Graphene",
	"SuperConductor",
	"StrangeEmitter",
	"Carbon",
	"Iron",
	"CopperOre",
	"ParticleAccelerator",
	"SurveyDataUnit",
	"Diamond",
	"Hydrocarbon",
	"RadiationAbsorber",
	"EnergySubstrate",
	"Framework",
	"CopperWire",
	"Polymer",
	"Electronics",
	"Magnet",
	"CrystalLattice",
	"Steel",
	"Arco",
	"Rochinol",
	"Fuel",
	"Food",
	"Toolkit",
	"Ammunition",
] as const;

export type ResourceName = (typeof resourceNames)[number];

export const resourceMintToName: Record<string, ResourceName> = {
	SiLiCA4xKGkyymB5XteUVmUeLqE4JGQTyWBpKFESLgh: "Silica",
	Nitro6idW5JCb2ysUPGUAvVqv3HmUR7NVH7NdybGJ4L: "Nitrogen",
	tiorehR1rLfeATZ96YoByUkvNFsBfUUSQWgSH2mizXL: "TitaniumOre",
	TTNM1SMkM7VKtyPW6CNBZ4cg3An3zzQ8NVLS2HpMaWL: "Titanium",
	aeroBCMu6AX6bCLYd1VQtigqZh8NGSjn54H1YSczHeJ: "Aerogel",
	FiELD9fGaCgiNMfzQKKZD78wxwnBHTwjiiJfsieb6VGb: "FieldStabilizer",
	LUMACqD5LaKjs1AeuJYToybasTXoYQ7YkxJEc4jowNj: "Lumanite",
	PoWRYJnw3YDSyXgNtN3mQ3TKUMoUSsLAbvE8Ejade3u: "PowerSource",
	EMAGoQSP89CJV5focVjrpEuE4CeqJ4k1DouQW7gUu7yX: "Electromagnet",
	HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp: "Hydrogen",
	CPPRam7wKuBkYzN5zCffgNU17RKaeMEns4ZD83BqBVNR: "Copper",
	MASS9GqtJz6ABisAxcUn3FeR4phMqH1XfG6LPKJePog: "Biomass",
	FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J: "IronOre",
	GRAPHKGoKtXtdPBx17h6fWopdT5tLjfAP8cDJ1SvvDn4: "Graphene",
	CoNDDRCNxXAMGscCdejioDzb6XKxSzonbWb36wzSgp5T: "SuperConductor",
	EMiTWSLgjDVkBbLFaMcGU6QqFWzX9JX6kqs1UtUjsmJA: "StrangeEmitter",
	CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X: "Carbon",
	ironxrUhTEaBiR9Pgp6hy4qWx6V2FirDoXhsFP25GFP: "Iron",
	CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc: "CopperOre",
	PTCLSWbwZ3mqZqHAporphY2ofio8acsastaHfoP87Dc: "ParticleAccelerator",
	SDUsgfSZaDhhZ76U3ZgvtFiXsfnHbf2VrzYxjBZ5YbM: "SurveyDataUnit",
	DMNDKqygEN3WXKVrAD4ofkYBc4CKNRhFUbXP4VK7a944: "Diamond",
	HYCBuSWCJ5ZEyANexU94y1BaBPtAX2kzBgGD2vES2t6M: "Hydrocarbon",
	RABSXX6RcqJ1L5qsGY64j91pmbQVbsYRQuw1mmxhxFe: "RadiationAbsorber",
	SUBSVX9LYiPrzHeg2bZrqFSDSKkrQkiCesr6SjtdHaX: "EnergySubstrate",
	FMWKb7YJA5upZHbu5FjVRRoxdDw2FYFAu284VqUGF9C2: "Framework",
	cwirGHLB2heKjCeTy4Mbp4M443fU4V7vy2JouvYbZna: "CopperWire",
	PoLYs2hbRt5iDibrkPT9e6xWuhSS45yZji5ChgJBvcB: "Polymer",
	ELECrjC8m9GxCqcm4XCNpFvkS8fHStAvymS6MJbe3XLZ: "Electronics",
	MAGNMDeDJLvGAnriBvzWruZHfXNwWHhxnoNF75AQYM5: "Magnet",
	CRYSNnUd7cZvVfrEVtVNKmXiCPYdZ1S5pM5qG2FDVZHF: "CrystalLattice",
	STEELXLJ8nfJy3P4aNuGxyNRbWPohqHSwxY75NsJRGG: "Steel",
	ARCoQ9dndpg6wE2rRexzfwgJR3NoWWhpcww3xQcQLukg: "Arco",
	RCH1Zhg4zcSSQK8rw2s6rDMVsgBEWa4kiv1oLFndrN5: "Rochinol",
	fueL3hBZjLLLJHiFH9cqZoozTG3XQZ53diwFPwbzNim: "Fuel",
	foodQJAztMzX1DKpLaiounNe2BDMds5RNuPC6jsNrDG: "Food",
	tooLsNYLiVqzg8o4m3L2Uetbn62mvMWRqkog6PQeYKL: "Toolkit",
	ammoK8AkX2wnebQb35cDAZtTkvsXQbi82cGeTnUvvfK: "Ammunition",
} satisfies Record<ResourceMint, ResourceName>;

export const resourceNameToMint = {
	Silica: new PublicKey("SiLiCA4xKGkyymB5XteUVmUeLqE4JGQTyWBpKFESLgh"),
	Nitrogen: new PublicKey("Nitro6idW5JCb2ysUPGUAvVqv3HmUR7NVH7NdybGJ4L"),
	TitaniumOre: new PublicKey("tiorehR1rLfeATZ96YoByUkvNFsBfUUSQWgSH2mizXL"),
	Titanium: new PublicKey("TTNM1SMkM7VKtyPW6CNBZ4cg3An3zzQ8NVLS2HpMaWL"),
	Aerogel: new PublicKey("aeroBCMu6AX6bCLYd1VQtigqZh8NGSjn54H1YSczHeJ"),
	FieldStabilizer: new PublicKey(
		"FiELD9fGaCgiNMfzQKKZD78wxwnBHTwjiiJfsieb6VGb",
	),
	Lumanite: new PublicKey("LUMACqD5LaKjs1AeuJYToybasTXoYQ7YkxJEc4jowNj"),
	PowerSource: new PublicKey("PoWRYJnw3YDSyXgNtN3mQ3TKUMoUSsLAbvE8Ejade3u"),
	Electromagnet: new PublicKey("EMAGoQSP89CJV5focVjrpEuE4CeqJ4k1DouQW7gUu7yX"),
	Hydrogen: new PublicKey("HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp"),
	Copper: new PublicKey("CPPRam7wKuBkYzN5zCffgNU17RKaeMEns4ZD83BqBVNR"),
	Biomass: new PublicKey("MASS9GqtJz6ABisAxcUn3FeR4phMqH1XfG6LPKJePog"),
	IronOre: new PublicKey("FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J"),
	Graphene: new PublicKey("GRAPHKGoKtXtdPBx17h6fWopdT5tLjfAP8cDJ1SvvDn4"),
	SuperConductor: new PublicKey("CoNDDRCNxXAMGscCdejioDzb6XKxSzonbWb36wzSgp5T"),
	StrangeEmitter: new PublicKey("EMiTWSLgjDVkBbLFaMcGU6QqFWzX9JX6kqs1UtUjsmJA"),
	Carbon: new PublicKey("CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X"),
	Iron: new PublicKey("ironxrUhTEaBiR9Pgp6hy4qWx6V2FirDoXhsFP25GFP"),
	CopperOre: new PublicKey("CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc"),
	ParticleAccelerator: new PublicKey(
		"PTCLSWbwZ3mqZqHAporphY2ofio8acsastaHfoP87Dc",
	),
	SurveyDataUnit: new PublicKey("SDUsgfSZaDhhZ76U3ZgvtFiXsfnHbf2VrzYxjBZ5YbM"),
	Diamond: new PublicKey("DMNDKqygEN3WXKVrAD4ofkYBc4CKNRhFUbXP4VK7a944"),
	Hydrocarbon: new PublicKey("HYCBuSWCJ5ZEyANexU94y1BaBPtAX2kzBgGD2vES2t6M"),
	RadiationAbsorber: new PublicKey(
		"RABSXX6RcqJ1L5qsGY64j91pmbQVbsYRQuw1mmxhxFe",
	),
	EnergySubstrate: new PublicKey("SUBSVX9LYiPrzHeg2bZrqFSDSKkrQkiCesr6SjtdHaX"),
	Framework: new PublicKey("FMWKb7YJA5upZHbu5FjVRRoxdDw2FYFAu284VqUGF9C2"),
	CopperWire: new PublicKey("cwirGHLB2heKjCeTy4Mbp4M443fU4V7vy2JouvYbZna"),
	Polymer: new PublicKey("PoLYs2hbRt5iDibrkPT9e6xWuhSS45yZji5ChgJBvcB"),
	Electronics: new PublicKey("ELECrjC8m9GxCqcm4XCNpFvkS8fHStAvymS6MJbe3XLZ"),
	Magnet: new PublicKey("MAGNMDeDJLvGAnriBvzWruZHfXNwWHhxnoNF75AQYM5"),
	CrystalLattice: new PublicKey("CRYSNnUd7cZvVfrEVtVNKmXiCPYdZ1S5pM5qG2FDVZHF"),
	Steel: new PublicKey("STEELXLJ8nfJy3P4aNuGxyNRbWPohqHSwxY75NsJRGG"),
	Arco: new PublicKey("ARCoQ9dndpg6wE2rRexzfwgJR3NoWWhpcww3xQcQLukg"),
	Rochinol: new PublicKey("RCH1Zhg4zcSSQK8rw2s6rDMVsgBEWa4kiv1oLFndrN5"),
	Fuel: new PublicKey("fueL3hBZjLLLJHiFH9cqZoozTG3XQZ53diwFPwbzNim"),
	Food: new PublicKey("foodQJAztMzX1DKpLaiounNe2BDMds5RNuPC6jsNrDG"),
	Toolkit: new PublicKey("tooLsNYLiVqzg8o4m3L2Uetbn62mvMWRqkog6PQeYKL"),
	Ammunition: new PublicKey("ammoK8AkX2wnebQb35cDAZtTkvsXQbi82cGeTnUvvfK"),
} satisfies Record<ResourceName, PublicKey>;
