export const resourceMints = [
  "SiLiCA4xKGkyymB5XteUVmUeLqE4JGQTyWBpKFESLgh",
  "Nitro6idW5JCb2ysUPGUAvVqv3HmUR7NVH7NdybGJ4L",
  "tiorehR1rLfeATZ96YoByUkvNFsBfUUSQWgSH2mizXL",
  "TTNM1SMkM7VKtyPW6CNBZ4cg3An3zzQ8NVLS2HpMaWL",
  "aeroBCMu6AX6bCLYd1VQtigqZh8NGSjn54H1YSczHeJ",
  "FiELD9fGaCgiNMfzQKKZD78wxwnBHTwjiiJfsieb6VGb",
  "LUMACqD5LaKjs1AeuJYToybasTXoYQ7YkxJEc4jowNj",
  "PoWRYJnw3YDSyXgNtN3mQ3TKUMoUSsLAbvE8Ejade3u",
  "EMAGoQSP89CJV5focVjrpEuE4CeqJ4k1DouQW7gUu7yX",
  "HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp",
  "CPPRam7wKuBkYzN5zCffgNU17RKaeMEns4ZD83BqBVNR",
  "MASS9GqtJz6ABisAxcUn3FeR4phMqH1XfG6LPKJePog",
  "FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J",
  "GRAPHKGoKtXtdPBx17h6fWopdT5tLjfAP8cDJ1SvvDn4",
  "CoNDDRCNxXAMGscCdejioDzb6XKxSzonbWb36wzSgp5T",
  "EMiTWSLgjDVkBbLFaMcGU6QqFWzX9JX6kqs1UtUjsmJA",
  "CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X",
  "ironxrUhTEaBiR9Pgp6hy4qWx6V2FirDoXhsFP25GFP",
  "CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc",
  "PTCLSWbwZ3mqZqHAporphY2ofio8acsastaHfoP87Dc",
  "SDUsgfSZaDhhZ76U3ZgvtFiXsfnHbf2VrzYxjBZ5YbM",
  "DMNDKqygEN3WXKVrAD4ofkYBc4CKNRhFUbXP4VK7a944",
  "HYCBuSWCJ5ZEyANexU94y1BaBPtAX2kzBgGD2vES2t6M",
  "RABSXX6RcqJ1L5qsGY64j91pmbQVbsYRQuw1mmxhxFe",
  "SUBSVX9LYiPrzHeg2bZrqFSDSKkrQkiCesr6SjtdHaX",
  "FMWKb7YJA5upZHbu5FjVRRoxdDw2FYFAu284VqUGF9C2",
  "cwirGHLB2heKjCeTy4Mbp4M443fU4V7vy2JouvYbZna",
  "PoLYs2hbRt5iDibrkPT9e6xWuhSS45yZji5ChgJBvcB",
  "ELECrjC8m9GxCqcm4XCNpFvkS8fHStAvymS6MJbe3XLZ",
  "MAGNMDeDJLvGAnriBvzWruZHfXNwWHhxnoNF75AQYM5",
  "CRYSNnUd7cZvVfrEVtVNKmXiCPYdZ1S5pM5qG2FDVZHF",
  "STEELXLJ8nfJy3P4aNuGxyNRbWPohqHSwxY75NsJRGG",
  "ARCoQ9dndpg6wE2rRexzfwgJR3NoWWhpcww3xQcQLukg",
  "RCH1Zhg4zcSSQK8rw2s6rDMVsgBEWa4kiv1oLFndrN5",
  "fueL3hBZjLLLJHiFH9cqZoozTG3XQZ53diwFPwbzNim",
  "foodQJAztMzX1DKpLaiounNe2BDMds5RNuPC6jsNrDG",
  "tooLsNYLiVqzg8o4m3L2Uetbn62mvMWRqkog6PQeYKL",
  "ammoK8AkX2wnebQb35cDAZtTkvsXQbi82cGeTnUvvfK",
] as const;

export type ResourceMint = (typeof resourceMints)[number];

export const resourceNames = [
  "Silica",
  "Nitrogen",
  "Titanium Ore",
  "Titanium",
  "Aerogel",
  "Field Stabilizer",
  "Lumanite",
  "Power Source",
  "Electromagnet",
  "Hydrogen",
  "Copper",
  "Biomass",
  "Iron Ore",
  "Graphene",
  "Super Conductor",
  "Strange Emitter",
  "Carbon",
  "Iron",
  "Copper Ore",
  "Particle Accelerator",
  "Survey Data Unit",
  "Diamond",
  "Hydrocarbon",
  "Radiation Absorber",
  "Energy Substrate",
  "Framework",
  "Copper Wire",
  "Polymer",
  "Electronics",
  "Magnet",
  "Crystal Lattice",
  "Steel",
  "Arco",
  "Rochinol",
  "Fuel",
  "Food",
  "Toolkit",
  "Ammunition",
] as const;

export type ResourceName = (typeof resourceNames)[number];

export const resourceMintToName = {
  SiLiCA4xKGkyymB5XteUVmUeLqE4JGQTyWBpKFESLgh: "Silica",
  Nitro6idW5JCb2ysUPGUAvVqv3HmUR7NVH7NdybGJ4L: "Nitrogen",
  tiorehR1rLfeATZ96YoByUkvNFsBfUUSQWgSH2mizXL: "Titanium Ore",
  TTNM1SMkM7VKtyPW6CNBZ4cg3An3zzQ8NVLS2HpMaWL: "Titanium",
  aeroBCMu6AX6bCLYd1VQtigqZh8NGSjn54H1YSczHeJ: "Aerogel",
  FiELD9fGaCgiNMfzQKKZD78wxwnBHTwjiiJfsieb6VGb: "Field Stabilizer",
  LUMACqD5LaKjs1AeuJYToybasTXoYQ7YkxJEc4jowNj: "Lumanite",
  PoWRYJnw3YDSyXgNtN3mQ3TKUMoUSsLAbvE8Ejade3u: "Power Source",
  EMAGoQSP89CJV5focVjrpEuE4CeqJ4k1DouQW7gUu7yX: "Electromagnet",
  HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp: "Hydrogen",
  CPPRam7wKuBkYzN5zCffgNU17RKaeMEns4ZD83BqBVNR: "Copper",
  MASS9GqtJz6ABisAxcUn3FeR4phMqH1XfG6LPKJePog: "Biomass",
  FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J: "Iron Ore",
  GRAPHKGoKtXtdPBx17h6fWopdT5tLjfAP8cDJ1SvvDn4: "Graphene",
  CoNDDRCNxXAMGscCdejioDzb6XKxSzonbWb36wzSgp5T: "Super Conductor",
  EMiTWSLgjDVkBbLFaMcGU6QqFWzX9JX6kqs1UtUjsmJA: "Strange Emitter",
  CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X: "Carbon",
  ironxrUhTEaBiR9Pgp6hy4qWx6V2FirDoXhsFP25GFP: "Iron",
  CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc: "Copper Ore",
  PTCLSWbwZ3mqZqHAporphY2ofio8acsastaHfoP87Dc: "Particle Accelerator",
  SDUsgfSZaDhhZ76U3ZgvtFiXsfnHbf2VrzYxjBZ5YbM: "Survey Data Unit",
  DMNDKqygEN3WXKVrAD4ofkYBc4CKNRhFUbXP4VK7a944: "Diamond",
  HYCBuSWCJ5ZEyANexU94y1BaBPtAX2kzBgGD2vES2t6M: "Hydrocarbon",
  RABSXX6RcqJ1L5qsGY64j91pmbQVbsYRQuw1mmxhxFe: "Radiation Absorber",
  SUBSVX9LYiPrzHeg2bZrqFSDSKkrQkiCesr6SjtdHaX: "Energy Substrate",
  FMWKb7YJA5upZHbu5FjVRRoxdDw2FYFAu284VqUGF9C2: "Framework",
  cwirGHLB2heKjCeTy4Mbp4M443fU4V7vy2JouvYbZna: "Copper Wire",
  PoLYs2hbRt5iDibrkPT9e6xWuhSS45yZji5ChgJBvcB: "Polymer",
  ELECrjC8m9GxCqcm4XCNpFvkS8fHStAvymS6MJbe3XLZ: "Electronics",
  MAGNMDeDJLvGAnriBvzWruZHfXNwWHhxnoNF75AQYM5: "Magnet",
  CRYSNnUd7cZvVfrEVtVNKmXiCPYdZ1S5pM5qG2FDVZHF: "Crystal Lattice",
  STEELXLJ8nfJy3P4aNuGxyNRbWPohqHSwxY75NsJRGG: "Steel",
  ARCoQ9dndpg6wE2rRexzfwgJR3NoWWhpcww3xQcQLukg: "Arco",
  RCH1Zhg4zcSSQK8rw2s6rDMVsgBEWa4kiv1oLFndrN5: "Rochinol",
  fueL3hBZjLLLJHiFH9cqZoozTG3XQZ53diwFPwbzNim: "Fuel",
  foodQJAztMzX1DKpLaiounNe2BDMds5RNuPC6jsNrDG: "Food",
  tooLsNYLiVqzg8o4m3L2Uetbn62mvMWRqkog6PQeYKL: "Toolkit",
  ammoK8AkX2wnebQb35cDAZtTkvsXQbi82cGeTnUvvfK: "Ammunition",
} satisfies Record<ResourceMint, ResourceName>;

export const resourceNameToMint = {
  Silica: "SiLiCA4xKGkyymB5XteUVmUeLqE4JGQTyWBpKFESLgh",
  Nitrogen: "Nitro6idW5JCb2ysUPGUAvVqv3HmUR7NVH7NdybGJ4L",
  "Titanium Ore": "tiorehR1rLfeATZ96YoByUkvNFsBfUUSQWgSH2mizXL",
  Titanium: "TTNM1SMkM7VKtyPW6CNBZ4cg3An3zzQ8NVLS2HpMaWL",
  Aerogel: "aeroBCMu6AX6bCLYd1VQtigqZh8NGSjn54H1YSczHeJ",
  "Field Stabilizer": "FiELD9fGaCgiNMfzQKKZD78wxwnBHTwjiiJfsieb6VGb",
  Lumanite: "LUMACqD5LaKjs1AeuJYToybasTXoYQ7YkxJEc4jowNj",
  "Power Source": "PoWRYJnw3YDSyXgNtN3mQ3TKUMoUSsLAbvE8Ejade3u",
  Electromagnet: "EMAGoQSP89CJV5focVjrpEuE4CeqJ4k1DouQW7gUu7yX",
  Hydrogen: "HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp",
  Copper: "CPPRam7wKuBkYzN5zCffgNU17RKaeMEns4ZD83BqBVNR",
  Biomass: "MASS9GqtJz6ABisAxcUn3FeR4phMqH1XfG6LPKJePog",
  "Iron Ore": "FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J",
  Graphene: "GRAPHKGoKtXtdPBx17h6fWopdT5tLjfAP8cDJ1SvvDn4",
  "Super Conductor": "CoNDDRCNxXAMGscCdejioDzb6XKxSzonbWb36wzSgp5T",
  "Strange Emitter": "EMiTWSLgjDVkBbLFaMcGU6QqFWzX9JX6kqs1UtUjsmJA",
  Carbon: "CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X",
  Iron: "ironxrUhTEaBiR9Pgp6hy4qWx6V2FirDoXhsFP25GFP",
  "Copper Ore": "CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc",
  "Particle Accelerator": "PTCLSWbwZ3mqZqHAporphY2ofio8acsastaHfoP87Dc",
  "Survey Data Unit": "SDUsgfSZaDhhZ76U3ZgvtFiXsfnHbf2VrzYxjBZ5YbM",
  Diamond: "DMNDKqygEN3WXKVrAD4ofkYBc4CKNRhFUbXP4VK7a944",
  Hydrocarbon: "HYCBuSWCJ5ZEyANexU94y1BaBPtAX2kzBgGD2vES2t6M",
  "Radiation Absorber": "RABSXX6RcqJ1L5qsGY64j91pmbQVbsYRQuw1mmxhxFe",
  "Energy Substrate": "SUBSVX9LYiPrzHeg2bZrqFSDSKkrQkiCesr6SjtdHaX",
  Framework: "FMWKb7YJA5upZHbu5FjVRRoxdDw2FYFAu284VqUGF9C2",
  "Copper Wire": "cwirGHLB2heKjCeTy4Mbp4M443fU4V7vy2JouvYbZna",
  Polymer: "PoLYs2hbRt5iDibrkPT9e6xWuhSS45yZji5ChgJBvcB",
  Electronics: "ELECrjC8m9GxCqcm4XCNpFvkS8fHStAvymS6MJbe3XLZ",
  Magnet: "MAGNMDeDJLvGAnriBvzWruZHfXNwWHhxnoNF75AQYM5",
  "Crystal Lattice": "CRYSNnUd7cZvVfrEVtVNKmXiCPYdZ1S5pM5qG2FDVZHF",
  Steel: "STEELXLJ8nfJy3P4aNuGxyNRbWPohqHSwxY75NsJRGG",
  Arco: "ARCoQ9dndpg6wE2rRexzfwgJR3NoWWhpcww3xQcQLukg",
  Rochinol: "RCH1Zhg4zcSSQK8rw2s6rDMVsgBEWa4kiv1oLFndrN5",
  Fuel: "fueL3hBZjLLLJHiFH9cqZoozTG3XQZ53diwFPwbzNim",
  Food: "foodQJAztMzX1DKpLaiounNe2BDMds5RNuPC6jsNrDG",
  Toolkit: "tooLsNYLiVqzg8o4m3L2Uetbn62mvMWRqkog6PQeYKL",
  Ammunition: "ammoK8AkX2wnebQb35cDAZtTkvsXQbi82cGeTnUvvfK",
} satisfies Record<ResourceName, ResourceMint>;
