name: docker-release
'on':
  workflow_dispatch: 
    inputs:
      tag:
        description: 'Tag to release'
        required: true

jobs:
  docker-stable-release:
    runs-on: ubuntu-latest
    permissions:
      actions: 'read'
      contents: 'read'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate tag and get SHA
        id: taginfo
        run: |
          TAG="${{ github.event.inputs.tag }}"

          if ! git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "❌ Tag '$TAG' does not exist."
            exit 1
          fi

          SHA=$(git rev-list -n 1 "$TAG")
          echo "✅ Found tag '$TAG' -> commit SHA: $SHA"

          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "ref_name=$TAG" >> $GITHUB_OUTPUT

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag as stable
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/atom-core:${{ steps.taginfo.outputs.ref_name }}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/atom-core:${{ steps.taginfo.outputs.ref_name }} ${{ secrets.DOCKER_HUB_USERNAME }}/atom-core:stable
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/atom-core:stable
          
