name: Tag atom version
'on':
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  tag-version:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git config --global user.email "13602797+emberist@users.noreply.github.com"
      - run: git config --global user.name "Emberist"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run release
        run: pnpm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
