name: Tag atom version
'on':
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag-version:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git user
        uses: fregante/setup-git-user@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run release
        run: pnpm run release
